/* tslint:disable */
/* eslint-disable */
/**
 * bestLib
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AuthorDtoBooksInner } from './author-dto-books-inner';

/**
 * 
 * @export
 * @interface AuthorCatalogOutputDataInner
 */
export interface AuthorCatalogOutputDataInner {
    /**
     * 
     * @type {string}
     * @memberof AuthorCatalogOutputDataInner
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof AuthorCatalogOutputDataInner
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof AuthorCatalogOutputDataInner
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof AuthorCatalogOutputDataInner
     */
    'picture': string;
    /**
     * 
     * @type {Array<AuthorDtoBooksInner>}
     * @memberof AuthorCatalogOutputDataInner
     */
    'books': Array<AuthorDtoBooksInner>;
}

