/* tslint:disable */
/* eslint-disable */
/**
 * bestLib
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthorDto
 */
export interface AuthorDto {
    /**
     * 
     * @type {string}
     * @memberof AuthorDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof AuthorDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof AuthorDto
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof AuthorDto
     */
    'picture': string;
}

