/* tslint:disable */
/* eslint-disable */
/**
 * bestLib
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateBookDtoChaptersInner
 */
export interface CreateBookDtoChaptersInner {
    /**
     * 
     * @type {string}
     * @memberof CreateBookDtoChaptersInner
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof CreateBookDtoChaptersInner
     */
    'content': string;
    /**
     * 
     * @type {number}
     * @memberof CreateBookDtoChaptersInner
     */
    'position': number;
}

