/* tslint:disable */
/* eslint-disable */
/**
 * bestLib
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface EbookOutputFunctions
 */
export interface EbookOutputFunctions {
    /**
     * 
     * @type {any}
     * @memberof EbookOutputFunctions
     */
    'getFile'?: any;
    /**
     * 
     * @type {any}
     * @memberof EbookOutputFunctions
     */
    'scrollToProgress'?: any;
    /**
     * 
     * @type {any}
     * @memberof EbookOutputFunctions
     */
    'scrollToChapter'?: any;
    /**
     * 
     * @type {any}
     * @memberof EbookOutputFunctions
     */
    'removeAllTextSelection'?: any;
    /**
     * 
     * @type {any}
     * @memberof EbookOutputFunctions
     */
    'injectStyle'?: any;
    /**
     * 
     * @type {any}
     * @memberof EbookOutputFunctions
     */
    'wrapReactionsInMarkTag'?: any;
}

