/* tslint:disable */
/* eslint-disable */
/**
 * bestLib
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EbookOutputChaptersInner } from './ebook-output-chapters-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { EbookOutputFunctions } from './ebook-output-functions';

/**
 * 
 * @export
 * @interface EbookOutput
 */
export interface EbookOutput {
    /**
     * 
     * @type {Array<EbookOutputChaptersInner>}
     * @memberof EbookOutput
     */
    'chapters': Array<EbookOutputChaptersInner>;
    /**
     * 
     * @type {EbookOutputFunctions}
     * @memberof EbookOutput
     */
    'functions': EbookOutputFunctions;
    /**
     * 
     * @type {string}
     * @memberof EbookOutput
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof EbookOutput
     */
    'picture': string;
}

