/* tslint:disable */
/* eslint-disable */
/**
 * bestLib
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FullBookCount } from './full-book-count';
// May contain unused imports in some cases
// @ts-ignore
import type { FullBookStatisticsInner } from './full-book-statistics-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { UserCatalogOutputDataInnerSelectedGenresInner } from './user-catalog-output-data-inner-selected-genres-inner';
// May contain unused imports in some cases
// @ts-ignore
import type { UserLibraryOutputReadingBooksInnerAuthor } from './user-library-output-reading-books-inner-author';

/**
 * 
 * @export
 * @interface FullBook
 */
export interface FullBook {
    /**
     * 
     * @type {string}
     * @memberof FullBook
     */
    'summary': string;
    /**
     * 
     * @type {string}
     * @memberof FullBook
     */
    'concept': string;
    /**
     * 
     * @type {string}
     * @memberof FullBook
     */
    'description': string;
    /**
     * 
     * @type {number}
     * @memberof FullBook
     */
    'readingTime': number;
    /**
     * 
     * @type {number}
     * @memberof FullBook
     */
    'rating': number;
    /**
     * 
     * @type {boolean}
     * @memberof FullBook
     */
    'isPublic': boolean;
    /**
     * 
     * @type {Array<UserCatalogOutputDataInnerSelectedGenresInner>}
     * @memberof FullBook
     */
    'genres': Array<UserCatalogOutputDataInnerSelectedGenresInner>;
    /**
     * 
     * @type {string}
     * @memberof FullBook
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof FullBook
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof FullBook
     */
    'picture': string;
    /**
     * 
     * @type {UserLibraryOutputReadingBooksInnerAuthor}
     * @memberof FullBook
     */
    'author': UserLibraryOutputReadingBooksInnerAuthor;
    /**
     * 
     * @type {string}
     * @memberof FullBook
     */
    'createdAt': string;
    /**
     * 
     * @type {string}
     * @memberof FullBook
     */
    'updatedAt': string;
    /**
     * 
     * @type {string}
     * @memberof FullBook
     */
    'authorId': string;
    /**
     * 
     * @type {boolean}
     * @memberof FullBook
     */
    'isRecommendable': boolean;
    /**
     * 
     * @type {FullBookCount}
     * @memberof FullBook
     */
    '_count': FullBookCount;
    /**
     * 
     * @type {Array<FullBookStatisticsInner>}
     * @memberof FullBook
     */
    'statistics': Array<FullBookStatisticsInner>;
}

