/* tslint:disable */
/* eslint-disable */
/**
 * bestLib
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Contact: Github repository
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ReactionOutputBookAuthor
 */
export interface ReactionOutputBookAuthor {
    /**
     * 
     * @type {string}
     * @memberof ReactionOutputBookAuthor
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof ReactionOutputBookAuthor
     */
    'name'?: string;
}

